"""empty message

Revision ID: 06880d3f0c24
Revises: e3d480e8aaa8
Create Date: 2023-08-26 20:56:09.703240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06880d3f0c24'
down_revision = 'e3d480e8aaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.Text(), nullable=True))
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
