"""empty message

Revision ID: 0d9d4d002734
Revises: 7e64d82a09da
Create Date: 2023-08-26 21:00:37.361638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9d4d002734'
down_revision = '7e64d82a09da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid2', sa.UUID(), nullable=True))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('uuid2')

    # ### end Alembic commands ###
