"""empty message

Revision ID: 123367a6bb37
Revises: 4827a22be703
Create Date: 2023-07-18 11:54:58.440252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123367a6bb37'
down_revision = '4827a22be703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
