"""empty message

Revision ID: 13ea1be821be
Revises: ffc4b3cac054
Create Date: 2024-05-26 18:16:58.205760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ea1be821be'
down_revision = 'ffc4b3cac054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['client_id'], ['id'])
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_company')
        batch_op.drop_column('customer_designation')
        batch_op.drop_column('customer_phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('secondary_phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('secondary_email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('zip')
        batch_op.drop_column('country')
        batch_op.drop_column('designation')
        batch_op.drop_column('address')
        batch_op.drop_column('company')
        batch_op.drop_column('secondary_email')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('phone')

    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_designation', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_company', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
