"""empty message

Revision ID: 395ddbb88bc3
Revises: 3f7584ea64f8
Create Date: 2023-06-21 15:52:04.022179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395ddbb88bc3'
down_revision = '3f7584ea64f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('validity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('grand_total',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('grand_total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('validity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
