"""empty message

Revision ID: 3f7584ea64f8
Revises: 
Create Date: 2023-06-21 14:56:00.820144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7584ea64f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('validity', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Integer(), nullable=False),
    sa.Column('grand_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    # ### end Alembic commands ###
