"""empty message

Revision ID: 5b610e36d9bb
Revises: a138f855e5dd
Create Date: 2023-06-21 17:31:49.469976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b610e36d9bb'
down_revision = 'a138f855e5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    with op.batch_alter_table('unit_quote', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_quote', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(),
               nullable=True)

    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pet_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pet_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pet_description', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_file', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pets_pkey')
    )
    # ### end Alembic commands ###
