"""empty message

Revision ID: 609e9c8af7a5
Revises: 5b610e36d9bb
Create Date: 2023-06-21 18:13:44.820909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609e9c8af7a5'
down_revision = '5b610e36d9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_info_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('unit_quote_unit_quote_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quote_info', ['quote_info_id'], ['id'])
        batch_op.drop_column('unit_quote_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_quote_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('unit_quote_unit_quote_id_fkey', 'quote_info', ['unit_quote_id'], ['id'])
        batch_op.drop_column('quote_info_id')

    # ### end Alembic commands ###
