"""empty message

Revision ID: 6ccb541d6188
Revises: d71f44a4b24e
Create Date: 2023-06-26 20:55:15.195085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccb541d6188'
down_revision = 'd71f44a4b24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grand_total2', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('grand_total2')

    # ### end Alembic commands ###
