"""empty message

Revision ID: a138f855e5dd
Revises: 56d91c71b10f
Create Date: 2023-06-21 16:36:27.712494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a138f855e5dd'
down_revision = '56d91c71b10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.Text(), nullable=True))
        batch_op.drop_column('imgage_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgage_file', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
