"""empty message

Revision ID: ad6b2a079013
Revises: 395ddbb88bc3
Create Date: 2023-06-21 16:01:19.323571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6b2a079013'
down_revision = '395ddbb88bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('shipping_cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('grand_total',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('grand_total',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
