"""empty message

Revision ID: b940ab097a5c
Revises: 
Create Date: 2024-05-23 22:24:11.295800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b940ab097a5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('quote_data', sa.JSON(), nullable=True),
    sa.Column('user_data', sa.JSON(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(), server_default='', nullable=False),
    sa.Column('first_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validity', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(), nullable=True),
    sa.Column('grand_total', sa.Numeric(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['quote.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.Text(), nullable=True),
    sa.Column('uploded_file', sa.Text(), nullable=True),
    sa.Column('transported_file', sa.Text(), nullable=True),
    sa.Column('material_search', sa.String(length=100), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('finishing', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('x_size', sa.Numeric(), nullable=True),
    sa.Column('y_size', sa.Numeric(), nullable=True),
    sa.Column('z_size', sa.Numeric(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('quote_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_info_id'], ['quote_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_quote')
    op.drop_table('quote_info')
    op.drop_table('quote')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
