"""empty message

Revision ID: ccd89f13f065
Revises: d0f285e94bd5
Create Date: 2024-05-25 09:51:45.133133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd89f13f065'
down_revision = 'd0f285e94bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_company', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_designation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_designation')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_company')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
