"""empty message

Revision ID: d0f285e94bd5
Revises: b940ab097a5c
Create Date: 2024-05-24 12:17:54.928826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f285e94bd5'
down_revision = 'b940ab097a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_info', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
