"""empty message

Revision ID: ef880332be46
Revises: 13ea1be821be
Create Date: 2024-05-26 18:25:08.940232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef880332be46'
down_revision = '13ea1be821be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_constraint('quote_client_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.create_foreign_key('quote_client_id_fkey', 'users', ['client_id'], ['id'])

    # ### end Alembic commands ###
