"""empty message

Revision ID: ffc4b3cac054
Revises: ccd89f13f065
Create Date: 2024-05-25 15:52:22.364965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc4b3cac054'
down_revision = 'ccd89f13f065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usd_to_rmb', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('commission')
        batch_op.drop_column('usd_to_rmb')

    # ### end Alembic commands ###
